CREATE DATABASE FileDB;
GO
USE FileDB;

CREATE TABLE UploadedFiles (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FileName NVARCHAR(255) NOT NULL,
    ParamA NVARCHAR(100) NOT NULL,
    ParamB NVARCHAR(100) NOT NULL,
    UploadedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE CsvRows (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FileId INT NOT NULL,
    RowNumber INT NOT NULL,
    Col1 NVARCHAR(255),
    Col2 NVARCHAR(255),
    Col3 NVARCHAR(255),
    CONSTRAINT FK_Csv_File FOREIGN KEY (FileId) REFERENCES UploadedFiles(Id)
);
GO
